SurajPratap10/Imagine_AI

views/home.ejs

1. There were different navbar on home and other pages, due to Bootstrap import clashes.
2. Cards Styling were clashing due to bootstrap.
Before:
After:
* Fixes: #194 *
Before: Navigation bar is bigger in height, Dalle OpenAI and Login are not centered
After:
You can also Check for the testing deployment below:
https://imagine-6grpasviu-pranavsikarwal.vercel.app/
This could be merged on priority, so that no more clashes on home.ejs are faced. (Removing bootstrap which caused clashes)

[Fixed]: Removed bootstrap clashes with navbar class

---

public/css/style.css
views/includes/footer.ejs

A lot of changes were made to the footer so I didn't change it to the footer I had suggested previously. I just made its background dark so it looks distinct.
Fixed the issue of extra spacing in other pages.
We can now customize some background for log in and other pages.
There is a small form spacing issue in Image generation i guess as in mobile view it looks like this :
And normally like this : 
I didn't make any changes to the form styling.
So if these changes are suited, you can merge them under issue #225

Made footer dark

---

views/includes/footer.ejs

- This PR is about centering the copyright section properly, but when i started to working i saw that the usage of inline-styles.
- In frontend we must want to avoid inline styles, because it's one of the good practices we want to follow.
- I added manual style rules in `style` and remove the inline-styles from the elements

🛠️ [FIX]: IMPROPER ALIGNMENT & REMOVED INLINE STYLES FOR COPYRIGHT TEXT

---

public/css/spinner.css
views/includes/PRE.ejs

🚫🔄 The issue of  visually jarring white screen with the plain text "Loading..." that appears when navigating to another page through the navbar 
_**To resolve this issue, I have made the following changes:**_
Removed the code snippet from the PRE.ejs file that was responsible for displaying the "Loading..." text and the associated loader element.
```javascript
<div id="PRE" class="bodyPRE">
<div class="loader">Loading...</div>
</div>
```
**_Tested the issue with low speed net and other condition ... It Fixed!!_**
https://github.com/SurajPratap10/Imagine_AI/assets/85815172/3ffd8cdc-b97e-45d1-b8d6-cc7b0091574a
https://github.com/SurajPratap10/Imagine_AI/assets/85815172/7b1ad66b-df24-439c-8a82-7adec65645fd

Loading Whitescreen Removed

---

readme.md

Added the Licenses section and the MIT license badge to the readme. It looks better now.

Added Licenses section and badge in readme

---

public/css/style.css
views/signup.ejs

Hey, @SurajPratap10 The buttons were fixed by someone else so I found another bug and fixed it. I have adjusted the height of the login and signup page. Previously the heading on these pages was not visible due to heard coded height of the forms. But now it is visible. Please review my pr and merge it. Thank you!
Before:-
After:-

Adjusted the height of the login and signup page

---

views/imagineAi.ejs
views/includes/sidebar.ejs

Added a side navbar on the ImagineAI page and change the hamburger style to make it visible on all pages.
closes #633 **[style Bug]: Navbar menu is hidden in Imagin-AI page for mobile size** 
https://github.com/SurajPratap10/Imagine_AI/assets/86224794/00bd6070-d406-4aba-8b81-85a42106ea6e

Navabar in imagineAI page

---

readme.md

- Improve readability of Imagine AI Documentation by replacing plain text based tech stack into attractive badges with links
- The user can navigate to the corresponding stack by clicking the image.
|||
|:---:|:---:|
|**BEFORE**|![image](https://user-images.githubusercontent.com/92252895/258851189-8a5f6331-64a1-4fa8-80bd-a6f4cf05ed48.png)|
|**AFTER**|![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/3d35237b-fa49-4b21-8259-c7945a7a5434)|

docs: replace tech stack words into attractive badges 📛 ✨ 

---

views/includes/footer.ejs

old footer:
new footer:
I remove the image because Home is already there in the quick link and make the gap less between the Contact Us and quick link from its description and change the background color with the bottom section so that they can match with each other.

Improving the footer 

---

readme.md

- Made GSSOC Banner responsive to light/dark github mode, enhances the readability of Imagine AI Documentation.
|        BEFORE - LIGHT MODE       |        BEFORE - DARK MODE      |
| ![Image](https://user-images.githubusercontent.com/92252895/258637226-e2cc4f0b-7de3-4624-ac30-2788ec1ee5f4.png) | ![Image](https://user-images.githubusercontent.com/92252895/258637150-0fd9cce1-c4dd-4e87-b64f-b19dcd1795ed.png) |
<br>
|        AFTER - LIGHT MODE       |        AFTER - DARK MODE      |
|![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/747d3a5d-d093-46bb-806f-32feafed3e64) | ![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/ff5429e7-ac49-460c-b42f-148d2ee3c45a) |

docs: made gssoc banner adaptive to github light/dark mode 🌞/🌚 ✨  

---

views/home.ejs
views/includes/sidebar.ejs

This pull request fixes two issues:
1. **Hamberger Menu Z-Index Issue**: Adjusted the z-index of the hammer menu to prevent it from being overlapped by other elements like images on mobile devices. This ensures that the menu remains visible and functional.
2. **Mobile Body Overflow Scroll Issue**: The mobile version had an overflow scroll in the x-direction due to the `<iframe>` element exceeding the screen width. The width of the iframe has been adjusted to fit within the viewport, preventing unnecessary scrolling.
- Fixes #1113  (Hammer Menu Z-Index Issue)
- Fixes #1115 (Mobile Overflow Scroll Issue)
| <img width="1280" alt="Screenshot 2024-10-02 at 2 22 37 AM" …

Fix Hamberger Menu Z-Index Issue and Mobile Overflow Scroll Due to Iframe Width

---

views/includes/sidebar.ejs

This pull request addresses the issue of the sidebar not collapsing when clicking the Hamburger Menu again on smaller screens.
- Fixed the issue where the sidebar did not close when clicking the Hamburger Menu for the second time.
- Fixes issue #1126 
| <img width="1280" alt="Screenshot 2024-10-03 at 7 26 56 PM" src="https://github.com/user-attachments/assets/8add92f1-f015-4ada-9e1c-9f64b461aefa"> | <img width="1280" alt="Screenshot 2024-10-03 at 7 27 06 PM" src="https://github.com/user-attachments/assets/7784d279-3008-440c-a752-bf782570caf8"> |

Fix: Sidebar Collapse via Hamburger Menu on Smaller Screens

---

views/login.ejs

This pull request addresses the issue with the social media icons on the login page. The icons have been resized to ensure they are properly visible and balanced across all screen sizes, improving the user experience and design consistency.
- Fixes issue #1130
- Increased the size of the social media icons for better visibility.
- Ensured responsive resizing for small to large screens to maintain consistency across devices.
- Adjusted alignment and spacing for a cleaner, more polished look.
| <img width="1280" alt="Screenshot 2024-10-03 at 8 04 13 PM" src="https://github.com/user-attachments/assets/3f2669ae-8773-4606-b2de-f420b1c3e9e3"> | <img width="1280" alt="Screenshot 2024-10-05 at 4 06 …

Fix: Adjust Social Media Icon Size on Login Page for All Screen Sizes

---

package-lock.json
views/contactUs.ejs
views/login.ejs

I have done some changes in the login page where the eye position was in the email button which was totally wrong so i placed it in the password button and I also styled the sign up button, changed the size of the social media icons too. Moreover in the contact us page one of the buttons at the bottom were overlapping with the other so I fixed i giving a margin top feature.
Hope you will accept my pull request . Thanks sir for giving me a chance to work for you.

Change in contactus and login page

---

views/team.ejs

This pull request addresses the issues outlined in the community page, making the site fully responsive and professional across all devices. The following changes have been implemented:
1. **Replaced Display Grid with Flexbox:**  
- Changed the layout structure to use flexbox instead of the grid system for better control and responsiveness.
- Added `flex-wrap` to allow items to wrap correctly on smaller screens.
2. **Fixed Heading Size:**  
- Updated the heading units from `vh` to `rem` and added responsive scaling to adjust the size based on the device, ensuring the heading looks appropriate on all screens.
3. **Enhanced Mobile View:**  
- Adjusted the flex properties and other CSS rules to make the page responsive for mobile devices.
- Ensured that all elements scale properly and align …

Fix Community Page Responsiveness and Enhance Design

---

views/home.ejs

This pull request enhances the user experience by adding interactive hover and focus effects to the input and button fields within the newsletter section. These changes include:
**Input Field:**
- Added a glow effect on focus for better visual feedback.
- Implemented a subtle glow effect on hover to indicate interactivity.
**Button:**
- Added a color glow on hover with scaling for a smoother transition.
**Changes Made:**
- Modified the input field to include focus and hover effects.
- Updated the button to scale and glow on hover.
**Testing:**
- Tested across multiple screen sizes to ensure responsiveness and consistent appearance.
- Checked hover and focus behaviors on different browsers (Chrome, Firefox, Edge).
fixes: #1199
Kindly merge it @SurajPratap10

Add Hover Effects for Input and Button Fields in Newsletter Section

---

views/contactUs.ejs

This pull request addresses the overflow and overlap issues of the contact us boxes on the Contact Us page. The changes made ensure that the boxes remain within the container and do not exceed the max width of the device, as well as provide adequate spacing to avoid overlapping with the contact us form.
- Adjusted the max-width property of the contact us boxes to ensure they fit within the device width and prevent overflow.
- Added padding and margins to maintain appropriate spacing between the boxes and the contact us form.
- Tested responsiveness across multiple screen sizes to ensure the fix works consistently.
Closes #1247 
- _Before_: 
- _After_: 
1. Verified the fix on various screen sizes (mobile, tablet, desktop).
2. Ensured that the boxes are contained within the device width and …

 Fix Overflow and Overlap Issue on Contact Us Page

---

views/home.ejs

**Description** 
I added an expand button to the section displaying sample images made by AI. This change enhances user interaction by allowing users to view larger versions of the images, making it easier to appreciate the details and quality of the AI-generated content. 
**How It Works:**
- Viewing Images: Click the expand button next to any sample image to view a larger version.
- Improved Clarity: This feature allows you to appreciate the details and quality of the AI-generated content more easily.
**Usage**:
- Navigate to the AI sample images section of the application.
- Click on the expand button for any image to see it in a larger format.
BEFORE
AFTER : 
@SurajPratap10  If change acceptable kindly merge and assign me this PR and **add labels : hacktoberfest-accepted, gssoc-ext, …

Added expand button for sample images

---

views/team.ejs

This pull request addresses the issue where the community section and footer section are touching each other, creating a lack of visual separation. A gap has been added to improve the layout and enhance the overall user experience.
- Added margin to the footer section to create a visual gap between the community section and the footer.
- Adjusted CSS styles to ensure consistent spacing across different screen sizes.
- **Before**: The community section and footer were directly adjacent with no spacing.
- **After**: A margin has been introduced, creating a clear separation between the two sections.

 Some Changes in text.ejs file

---

views/includes/navbar.ejs
views/team.ejs

We implemented a dark mode feature to enhance user experience by allowing users to switch between light and dark themes. This update included a "Toggle Theme" button and dynamic styling for the .heading-contributors class, which changes the text color to white in dark mode for better visibility. The CSS was updated to support this new design, and JavaScript was used to manage the theme toggling by applying a .dark-mode class to the <body> element. These changes aim to improve usability and the overall aesthetic of the community section.
- [x ] Tests have been added or updated to cover the changes
- [x ] Code follows the established coding style guidelines

Activated Dark theme in community page and also the text

---

public/css/style.css
views/includes/sidebar.ejs

This pull request addresses the issue where the Hamburger Menu and Dark Mode Toggle were overlapping at certain screen sizes, causing usability issues. The fix sets a breakpoint at `1180px` to prevent these elements from overlapping and ensures the UI remains smooth and consistent across all screen sizes.
- Updated the CSS to set a breakpoint at `1180px` for the navbar.
- Adjusted the positioning and margins of the Hamburger Menu and Dark Mode Toggle to prevent overlap.
- Tested on different screen sizes to ensure the UI remains responsive and elements are properly spaced.
Fixes: #1150 
| <img width="386" alt="Screenshot 2024-10-15 at 11 09 07 AM" …

Fix Responsiveness Issues and Overlap of Hamburger Menu and Dark Mode Toggle

---

public/css/style.css

This pull request addresses the issues identified on the privacy policy page when viewed on mobile devices. The changes made include:
- **Overflow Fix**: Removed unnecessary grid structure and adjusted CSS to eliminate the Y-axis overflow, ensuring smooth scrolling and better navigation.
- **Content Visibility**: Corrected layout settings to make sure all content is fully visible on mobile screens, preventing elements from being cut off.
- **Padding Adjustment**: Reduced excessive padding around elements to create a more streamlined and mobile-friendly appearance, enhancing readability.
- Closes #1220
- Removed unnecessary grid and applied a flex layout to maintain content alignment and visibility.
- Adjusted CSS padding values to maintain consistency with mobile design standards.
| …

Fix Privacy Policy Page Responsiveness on Mobile Devices

---

views/includes/footer.ejs

**# Description**
I have fixed the issue in the "Subscribe Us" section where the horizontal line appeared too far below the input field and submit button, leading to a disjointed appearance. The styling for margin and padding has been adjusted to reduce the unnecessary spacing, ensuring consistent spacing for a cleaner and more unified look.
**## Fixes** #1261
This pull request addresses issue #1261 , improving the layout and user experience.
**## Screenshots**
|        BEFORE        |       
| ![Image](after-image-link) 
|        AFTER         |
**## Checklist**
- [x ] Tests have been added or updated to cover the changes.
- [x ] Documentation has been updated to reflect the changes.
- [x ] Code follows the established coding style guidelines.
- [x ] All tests are passing.
--- …

Subscribe section bottom line closer to input field

---

config/db.js

// i just made some changes so that it can add connection options to improve performance and handle potential issues and want to log more details about the error, such as the error code so that it ,may create more easiness and reusble of code.
| ![Image](image-link) | ![Image](image-link) |

IMAGINE AI Update db.js

---

package-lock.json
views/aboutUs.ejs
views/alan.ejs
views/contactUs.ejs
views/feedback.ejs
views/forgot-password.ejs
views/home.ejs
views/imagineAi.ejs
views/intro.ejs
views/login.ejs
views/privacypolicy.ejs
views/signup.ejs
views/slider.ejs
views/team.ejs

https://github.com/user-attachments/assets/20f39a3b-2846-4d9c-ada6-36435b17b031
@SurajPratap10 please review this pr thanks!
| ![Image](image-link) | ![Image](image-link) |

fixed text overlapping in language translator

---

public/css/style.css

Fixes #1311
This pull request adds a 3D hover effect to the "Enter your email ID" input box, enhancing its interactivity and visual appeal. The input box now slightly scales up with a shadow effect when hovered over, giving a 3D appearance. Additionally, the border color and shadow are adjusted when the input is focused for a more refined user experience. No external dependencies are required for this change.
**Before**
**After**

[style]: Adding hover effect on "Enter your email ID" box
