SurajPratap10/Imagine_AI

- public/css/style.css
closes #3 
- Radius is given to Generate Button
- Fixed hover problem in the button
On Hover -
> (#3) Generate Button Border Radius

- package-lock.json
- public/css/spinner.css
- public/css/style.css
- public/index.html
- public/js/main.js
Added the copyright and the github profile link of the owner. Also i made the font synchronous
> Updated the website

- public/css/style.css
I have resolved the cursor bug. Now it is text cursor instead of pointer cursor.
Please review the changes and merge the pull request.
> fixed cursor bug

- public/css/style.css
- public/index.html
Issue #26 Fixed Now it works fine in both screen (Big and Small Screen)
> Paragraph Tag Size in Small Screen #26 Fixed 

- index.js
issue solved  #27 .  Added an  error handling middleware in the Express application to catch and handle errors. Demonstrated  by adding a test route that intentionally throws an error. The error is caught by the error handling middleware.
https://1drv.ms/i/s!AsQPp0hrCv-Cga01JkG_hY_v4-RJkw?e=RNZJct
> Added error handler in index.js

- public/css/style.css
- public/index.html
I have added the about page. Please review it and merge the pull request.
> added about page

- readme.md
Issue#36
I have added contributors section in Readme.md, please have a look at it.
> Added contributors in Readme Issue #36

- .env
- controllers/openaiController.js
- public/js/main.js
Hey I have solved the issue. Now by giving an API_KEY, client can view the generated image.
Now if the API_KEY is valid and still active, client can view the generated image that client has prompted and mentioned the size.
> Issue#23: Adding_Functionality_to_Enter_Your_API_Key_section

- public/css/style.css
- public/index.html
issue #35 
I have centred the generate button text in the style.css file
Here's how it looks after the changes being applied to it :
> Fixed issue #35 - Center Generate button text

- public/css/style.css
- public/index.html
- public/js/main.js
https://github.com/SurajPratap10/Imagine_AI/assets/76244494/1773213e-2719-4338-a729-e9780fd1a754
> Implement #7

- public/css/style.css
- public/index.html
I have made changes to the buttons made them in accurate alignment for every media width and added flow behavior to the surprise Me button. If you want any more changes to be done in the front-end part of the website I would be happy to help 
Regards Priyam Maini
> Button changes

- public/css/style.css
Fixed unequal text issue. Kindly review it and merge the pull request
> fixed unequal text issue

- public/login.html
Have added the latest footer and navbar on sign in page
> Added footer and navbar in login page

- public/signup.html
Made the changes to sign up page too
> Added footer and navbar to signup

- public/js/main.js
Now you can see that null pointer error has been removed.
> main.js issue #113 fixed

- public/signup.html
Now  input tag has it's correct type
You can in SS at line 46 and 49.
> SignUp Page issue fixed

- public/css/style.css
- views/contactUs.ejs
we can see my changes in video.
https://github.com/SurajPratap10/Imagine_AI/assets/99237795/ed033aa7-38d8-4f4b-8e21-907ef2257906
> Contact page need improvement #99 fixed

- readme.md
**This Pull Request makes the following changes:**
* Fixes Issue: #123 
* Link to documentation of each tech stack is further attached*
This will help the newbie contributors.
Image below displays their look:
> readme tech stack modify

- readme.md
> changed git clone command

- public/css/style.css
- views/includes/header.ejs
Improvement of navbar and home page design #126 Fixed. Me and @Ks103 have redesign the navbar. you can see in the video below.
https://github.com/SurajPratap10/Imagine_AI/assets/99237795/b4d1e945-dc5b-4a5f-9889-95718aacd479
> Improvement of navbar and home page design #126 Fixed

- views/privatepolicy.html
Added all guideline of standard privacy policy. Have made it into a html page as I am not familiar with ejs much, so didn't want to create any conflicts. Please go through the policy and tell if any more guidelines needs to be added. After someone includes it's route in the viewroute, if needed I'll make a PR with its stylings. Thanks
> Added all privacy policy terms

- public/css/style.css
- views/home.ejs
Hiii
I made the following changes on the about page as promised:
fixed the allignment of heading and the text.
adjusted the spacing between elements.
made the whole page 100% responsive.
did few changes to make the UI/UX look better for the user experience.
please let me know if you want to change anything.
Thank You
> segmentation fixed

- public/css/style.css
- views/contactUs.ejs
Now Submit button position has been fixed.
> Contact Page Submit Button #142 Fixed

- public/css/style.css
- views/includes/footer.ejs
- views/includes/header.ejs
I have added a responsive navbar for all the media widths and kept the page's background in mind. Please check it out if there are any changes you want me to make kindly tell me.
Regards Priyam Maini
ps: I think I made the push from the origin and not from remote I am sorry and hope it won't be a problem if it is please guide me on what to do next.
> Responsive NavBar Added

- public/css/style.css
- views/includes/footer.ejs
- views/includes/header.ejs
Reverts SurajPratap10/Imagine_AI#136
> Revert "Responsive NavBar Added"

- public/css/style.css
- views/includes/header.ejs
hi @SurajPratap10 thank you so much for being patient with me, I have made a new navbar with a different approach, please check it out if there are any issues I will fix them immediately. 
regards priyam maini
> New Responsive Navbar added 

- public/css/style.css
- views/includes/header.ejs
Reverts SurajPratap10/Imagine_AI#153
> Revert "New Responsive Navbar added "

- views/login.ejs
Now Password is hidden from user until he/she want to see
> Input tag in Sign in page #150 Fixed

- public/js/main.js
> Error on Signup and Login Page 

- routes/viewRoutes.js
- views/privacypolicy.ejs
Converted into ejs file and added route
> Made privacypolicy into ejs

- CODE_OF_CONDUCT.md
Fixes issue #177 
@SurajPratap10  I've created the Code of Conduct file
> CODE_OF_CONDUCT.md File Created

- package-lock.json
- public/css/style.css
https://github.com/SurajPratap10/Imagine_AI/assets/83742554/34b186ae-0617-4a47-b817-4bd28eda0ca7
> Update in Example Section

- package-lock.json
- public/css/style.css
- routes/viewRoutes.js
- views/contactUs.ejs
- views/home.ejs
- views/imagineAi.ejs
- views/includes/header.ejs
- views/includes/navbar.ejs
- views/login.ejs
- views/privacypolicy.ejs
- views/signup.ejs
**This pull request made the following changes**
* Fixes #162*
**Basically there were two major problems**
1- Some PR added Bootstrap support so they made a redundant Header and navigation on home page.
-this was indeed a serious issue as this increases redundancy in any project and can lead to conflicts.
2- Activeness of Navigation button was therefore lost due to some erroneous styling change hence added it again, addition to it some unwanted bugs appeared on generate image page. 
Before Additon:
After addition:
To refer my testing deployment you can refer: 
https://imagine-ai-1xi2-pa15vlshc-pranavsikarwal.vercel.app/
> [Bug: Fix] Navbar fixed and Redundancy removed

- public/css/style.css
Now Navbar is responsive you can see the responsiveness of navbar in below video:
https://github.com/SurajPratap10/Imagine_AI/assets/99237795/72e33553-afa6-4f13-bfef-6275d578a080
> Navbar Responsiveness #185 Fixed

- public/css/style.css
- views/privacypolicy.ejs
Added uniform styles to privacy policy page
> Added styles to privacy policy

- public/css/style.css
- views/home.ejs
Reverts SurajPratap10/Imagine_AI#196
> Revert "animated cards added"

- public/css/style.css
- views/includes/footer.ejs
HI @SurajPratap10, I have made the footer for website #110 
**features added:**
1. navigation links to multiple pages
2. responsive
3. subscribe to the newsletter, connected to google sheets to store the user emails .
4. hover over links 
5. thanks for sub, it only appears when send is pressed (email required for it)
**Regarding Google Sheets:**
Please share your email id so I can give you access to the sheet which stores the emails.
Email id and phone number: the section mentions your email id you can add that later please add these later currently there is (no refresh) empty href tag
Can this be a Level 3 issue?
> Footer added #110

- public/css/style.css
- views/includes/footer.ejs
Reverts SurajPratap10/Imagine_AI#195
> Revert "Footer added #110"

- public/css/style.css
- views/includes/footer.ejs
hi @SurajPratap10, i have checked the code and it is working fine please check
> Footer checked

- public/css/style.css
- views/includes/footer.ejs
Reverts SurajPratap10/Imagine_AI#205
> Revert "Footer checked"

- public/css/style.css
- views/home.ejs
> cards animated

- public/css/style.css
- views/home.ejs
Reverts SurajPratap10/Imagine_AI#204
> Revert "cards animated"

- public/js/login.js
- public/js/signup.js
Now You can See in console (below) there are no error related to Signin.js and Login.js file.
> Signup and login JS error #210 Issue Fixed

- public/css/style.css
Added a css rule for textarea to have a sans-serif font.
#228
> Fixing the textarea font to sans-serif

- public/js/signup.js
> fixes contact page bug

- controllers/openaiController.js
- public/css/style.css
- public/js/main.js
- server throws more valuable errors so that frontend can show more detail of whats happening over the modal not just "There is error"
- Added Regex Validation to API key and fixed some code
- Fixed the poppup overflow
> Fix : validate openAI key and detailed warnings

- package-lock.json
- public/css/style.css
- public/js/main.js
- views/contactUs.ejs
- views/home.ejs
- views/imagineAi.ejs
- views/includes/PRE.ejs
- views/login.ejs
- views/privacypolicy.ejs
- views/signup.ejs
preloader with animation added
- [yes ] Tests have been added or updated to cover the changes
- [yes ] Documentation has been updated to reflect the changes
- [yes ] Code follows the established coding style guidelines
- [yes ] All tests are passing
> preloader added

- package-lock.json
- views/login.ejs
The password field was not hidden so people could see your password. I fixes the issue
Before:
After
> password field was not hidden, The issue is fixed [GSSoC'23]

- package-lock.json
- public/css/style.css
- public/js/main.js
- views/home.ejs
Tasks Completed are described below :
Files Updated :
- home.ejs
- main.js
- style.css
- navbar.ejs
Screenshot of Login Icon:
This PR is created in reference to Issue No.: #173
> [FEATURE] Added Transition Effect while Scrolling

- public/css/style.css
Submit button is not aligned properly, it is overlapping with other content on the page.
I fixed this issue
#239
> Issue with contact us Page #239

- package-lock.json
- package.json
- views/includes/footer.ejs
hey @SurajPratap10 
I have re-forked the repo and added the required changes kindly check.
> footer added

- public/css/errorStyle.css
- public/error.html
Back to Homepage button added on 404 page to navigate back to the homepage. The button styling is in sync to the whole application and nothing in the styling of the button has been changed. The height and width of the rocket svg has been reduced to avoid scrolling for viewing the button in some devices.
Fixes #250
> Add Back to Homepage button on 404 page

- public/css/style.css
- views/includes/footer.ejs
Reverts SurajPratap10/Imagine_AI#268
> Revert "Made footer dark"

- .env
- controllers/googleAuthContoller.js
- index.js
- package-lock.json
- package.json
- views/login.ejs
- views/signup.ejs
> Oauth added

- public/css/style.css
- views/includes/navbar.ejs
I changed the font of the about section which was not looking good and added an hover effect in the navbar.
Closes #221 
BEFORE:
-> Changed the font and added hover effect on the navbar.
AFTER:
> added hover effect on navbar + better fonts

- public/css/style.css
fixes #276 
https://github.com/SurajPratap10/Imagine_AI/assets/98143022/f9457c3a-169c-44ad-9b8c-893b0734188d
> feat: Sticky navbar added

- views/includes/footer.ejs
Email validation has been added to the Subscribe to us section.
> Email validation added

- views/includes/header.ejs
Added meta tags that increase the SEO of the website.
> Meta tags added

- views/home.ejs
- views/imagineAi.ejs
Added alt attributes to all img tags that did not contain them.
> Alt attributes added

- views/contactUs.ejs
Added validation to all form inputs on the Contact Us page.
> Contact Us form validation added

- public/css/style.css
- views/imagineAi.ejs
I've added the FAQ Section, 5 questions have been added, through a section created in ImagineAI.ejs file, I've added box shadow required spacing and catchy heading and Font SIze, it's completely responsive in all devices i.e media query added, toggle option present .
- [  ] Tests have been added or updated to cover the changes
- [  ] Code follows the established coding style guidelines
@SurajPratap10 could you please review this pull request
> Adding FAQ Section

- views/aboutUs.ejs
*Typo error solved ("Peple" to "People"). Please review the changes.*
@SurajPratap10 Thank you for this opportunity.
> Typo error solved

- public/css/style.css
- views/login.ejs
- views/signup.ejs
Add: 
- Google button, facebook button, twitter button (icons) for OAuth login and signup.
Now, OAuth is required for facebook and twitter as well. @SurajPratap10 
Before changes:
After changes:
> [Add]: Icons/Buttons for OAuth (sign in/ sign up)

- readme.md
changes made 
1. added a proper image of the website
2. added styling to the image
3. The name of the website was not in center, fixed it
Replace #359  with the issue number which is fixed in this PR
> Aman singh6574 issue#359

- public/css/style.css
- views/includes/navbar.ejs
A clean navbar is very important for an application as it is a crucial element. So to make it look great, the unwanted transitions are removed, smooth transitions are applied and soft colours are used.
The change/enhancement looks good with all background combinations and provides a clean look with smooth hover effects and soft colors.
looks good with all background combinations and provides a clean look with smooth hover effects and soft colors.
looks good with all background combinations and provides a clean look with smooth hover effects and soft colors.
> changes-in-navbar

- views/includes/footer.ejs
Change the color of placeholder text to white and background color of button to transparent.
Changed to color of text of placeholder of input tag to white and removed the black background of button of "Subscribe Us" section.
#363
> Fix color of elements of "Subscribe Us" section.

- public/css/style.css
Fix the font distortion that occur in the enter email #362
> Fix the enter email bug #362

- public/css/style.css
- public/js/validation.js
- views/includes/header.ejs
- views/login.ejs
- views/signup.ejs
This PR contains the code for implementing inline validation in the login and signup form.
https://github.com/SurajPratap10/Imagine_AI/assets/86224794/0e72a2a5-3a26-4680-a9cf-a16e8bdfe121
> Inline validation

- views/includes/navbar.ejs
Have fixed the issue and now its working fine. Issue #373
> fixes path in navbar

- .github/workflows/linting.yml
Added a github action that will automatically format the code using the linter workflow.
For the linter to run successfully please open the settings of the repo go to Actions -> General -> workflow permissions and enable read and write permissions.
> Automatic Code Prettier

- public/css/style.css
Have made the Placeholder visible. Thanks.
> Changed the placeholder visibility

- public/css/style.css
I have added the code for the alignment of icons in the User feedback box in About Us page.
> Added code for Icon alignment

- .github/workflows/close_old_issues.yml
Added a github action to close the old issues automatically after inactivity of 20 days.
> GitHub Action to close issues

- public/css/style.css
- views/includes/footer.ejs
I have added the code for the Icon hover transition bug in the footer section.
> Added code for Icon hover in footer

- public/css/style.css
- views/aboutUs.ejs
- views/home.ejs
About Us page modified with changes in layout and interactions(hover) making the UI impressive and clean with a smooth user experience.
about us page after changes :
hover effect over cards:
https://github.com/SurajPratap10/Imagine_AI/assets/92749015/8f8bd24e-fe17-4558-9ddd-c9919031827e
> changes-about-us-page

- views/includes/footer.ejs
- views/includes/header.ejs
Added new SEO tags that will optimize the SEO, Search Ranking.
By adding important SEO tags such as meta title, meta description, and heading tags to our web pages, we can provide search engines with relevant information about the content and context of each page. These tags help search engines understand the purpose of our pages and match them with relevant user queries.
Improved Search Engine Visibility: Including SEO tags ensures that search engines can effectively crawl and index our web pages, leading to better visibility in search results.
Higher Click-Through Rates (CTR): Well-optimized meta titles and descriptions can attract users' attention in search results, increasing the likelihood of them clicking on our pages.
Enhanced User Experience: SEO tags, such as heading tags, help …
> Critical SEO Tag Implementation Issues: missing tags which effect Search Engine Visibility and Performance #297

- models/users.js
Reverts SurajPratap10/Imagine_AI#354
> Revert "Solving Google Login issue"

- models/users.js
Reverts SurajPratap10/Imagine_AI#443
> Revert "Revert "Solving Google Login issue""

- models/users.js
Reverts SurajPratap10/Imagine_AI#444
> Revert "Revert "Revert "Solving Google Login issue"""

- public/error.html
Redesigning the 404 Page for Improved User Experience, current page UI lags
Benefits:
Enhanced user experience: A well-designed and visually consistent 404 page improves user experience by maintaining the overall look and feel of the website. Users will feel more confident and reassured, even when encountering errors or broken links.
Brand consistency: The upgraded 404 page ensures brand consistency throughout the website, reinforcing the website's identity and creating a cohesive experience for users.
Increased user engagement: By providing helpful suggestions or links on the 404 page, users are encouraged to explore other parts of the website, reducing bounce rates and increasing overall user engagement.
Positive perception: A visually appealing and user-friendly 404 page leaves a …
> Redesigning the 404 Page for Improved User Experience, current page UI lags

- views/imagineAi.ejs
Please merge my PR!!  Fixes #420
> Imagine-AI Image Description aligned properly

- .env
- views/includes/navbar.ejs
Changed the position of Dark/Light Toggle Button from left corner to Navbar.
Original:
> Changed Position of Dark/Light Toggle Button

- views/aboutUs.ejs
- views/contactUs.ejs
- views/home.ejs
- views/imagineAi.ejs
- views/includes/sidebar.ejs
- views/login.ejs
- views/privacypolicy.ejs
- views/signup.ejs
Enhance the responsiveness of the website by implementing a sidebar for small devices. Introduce a visually appealing hamburger icon that becomes visible when viewed on small devices. Upon clicking the hamburger icon, smoothly slide the sidebar in from the side, providing easy navigation options to the user. This improvement will enhance the overall user experience and make the website more accessible on different screen sizes.
https://github.com/SurajPratap10/Imagine_AI/assets/119161467/7fb6b6db-ddc8-446f-b1f5-f5d8c282fbfe
> Added SideBar for Small device with hamburger icon

- package-lock.json
- views/login.ejs
Changes made : 
- Fixed top margin of sign in form
- fixed show password alignment
- fixed height of overall form
> fix: sign in page

- robots.txt
Adding a robots.txt file allowing no bots or agents to crawl through the website.
> Added robots.txt file

- public/css/style.css
- views/contactUs.ejs
- views/includes/footer.ejs
> improved contact page - #452 PR conflits resolved

- views/home.ejs
- views/includes/navbar.ejs
Enhanced the navbar layout and styling. Also organized the dark mode toggle to suit better with the User Interface.
> navbar-enhanced

- views/includes/header.ejs
- Added open graph & twitter meta elements which plays a crucial role in terms of search engine optimization
- Added every necessary elements and grouped them together by their names with comments
> [ADD]: OPEN GRAPH & TWITTER META ELEMENTS ✨

- views/includes/footer.ejs
added the popup and feedback msg
- Added the popup feedback message when clicking on the EMAIL && PHONE NUMBER.
- Added the Thank you message when Subscribe form submitted
**make Contact us section Functional: Interactive Phone Number and Email Integration**
https://github.com/SurajPratap10/Imagine_AI/assets/99162236/afbf6cb7-92ff-483b-8fed-5eeaf4c19589
> make Contact us section Functional: Interactive Phone Number and Email Integration

- views/signup.ejs
Refactored the stylings of Signup page which were overlapping the footer and hiding behind the navbar.
Now the page is made consistent with appropriate responsiveness over different sizes.
* Fixes #490 
[screen-capture (14).webm](https://github.com/SurajPratap10/Imagine_AI/assets/113239388/06440c90-332f-4d24-8282-e70f77daa33c)
> redesigned signup page

- public/css/style.css
- public/js/validation.js
- views/contactUs.ejs
Added Inline validation in the contact form. 
https://github.com/SurajPratap10/Imagine_AI/assets/86224794/4d9bbdad-126b-4a46-8183-2a778a6624dc
> contact-validation

- public/css/style.css
Enhance the visual appeal and optimize user experience by revamping the UI of the FAQ section on the website. This pull request proposes a comprehensive overhaul of the existing FAQ design, aiming to create an aesthetically pleasing and user-friendly interface. By implementing improved styling, intuitive navigation, and clear categorization of frequently asked questions, this enhancement seeks to provide users with a seamless and satisfying experience when accessing and interacting with the FAQ section.
https://github.com/SurajPratap10/Imagine_AI/assets/119161467/097ad495-8ac5-4df1-bf14-81c7530971ec
> Improve the  FAQ Section

- public/css/style.css
- public/js/main.js
- views/includes/PRE.ejs
- `public/css/style.css`
- `public/js/main.js`
- `views/includes/PRE.ejs`
[IMAGINE---AI-Unleashing-the-Power-of-DALL-E-2-to-Generate-Stunning-One-of-a-Kind-Images.webm](https://github.com/SurajPratap10/Imagine_AI/assets/130365071/f8291843-a53d-420f-bb82-10c3274dbf03)
> style: improve loader animation

- public/css/style.css
- views/home.ejs
- views/includes/footer.ejs
The newsletter section in the home page is fixed.
> Newsletter section modified

- views/includes/footer.ejs
The year in footer section is made dynamic using js.
> Fixes year in footer

- public/css/style.css
- views/aboutUs.ejs
- views/contactUs.ejs
- views/home.ejs
- views/includes/navbar.ejs
Fixes navbar alignment and functionality
> fix(navbar): fixing navbar style and functionality

- public/error.html
- views/aboutUs.ejs
- views/contactUs.ejs
- views/home.ejs
- views/imagineAi.ejs
- views/includes/footer.ejs
- views/includes/navbar.ejs
Added lazy loading attribute to all img tags which improves performance of the website.
> Added lazy loading to img tags

- public/css/style.css
- public/js/main.js
- views/imagineAi.ejs
**Description**:
This pull request includes two enhancements for the `imagine_ai` project:
1. **Adding Sharing Button**: Implement a sharing functionality that allows users to share the image URL generated on our website. This feature will enable users to easily share the image with others through various social media platforms and communication channels.
2. **Fixing Image Positioning in FAQ Section**: Currently, the image appears below the Frequently Asked Questions (FAQ) section. This pull request aims to improve the visual appeal and user experience by positioning the image alongside the FAQ section. This change will associate the image with the relevant FAQ content, providing better context for users.
**Changes Made**:
1. Added a sharing button component to the user interface.
2. …
> Adding Sharing Button and Fixing Image Positioning

- views/includes/footer.ejs
Changed twitter icon and youtube icon to facebook and instagram icons respectively.
> changed to the icons

- package-lock.json
- package.json
- public/css/style.css
> IMAGINE-AI section enhanced

- public/css/style.css
- views/includes/footer.ejs
Left to right underline animation hover effect added on the footer content
https://github.com/SurajPratap10/Imagine_AI/assets/83147410/7dc6870a-2acf-455d-a62a-6a6be3485bf6
> Hover effect added on the footer element

- .github/workflows/lock.yml
This repository contains a workflow called `lock.yml` in the `.github/workflows` directory. The workflow is designed to reduce notifications when a maintainer adds a label, and allows for conversation unlocking until it is locked again.
N/A
> feat: create workflow ⚡

- .github/workflows/prevent_multiple_issues.yml
- This PR is about adding workflow script which helps us to prevent multiple issues created by a single contributer.
- The script will look for existing issue whenever a contributor creates a new issue, if existing issue is already there to work then the newly created issue will be closed.
- This will ensure us to follow the Open Source Contributing guidelines, and make the game more fair by providing chance for every contributors out there to make their first contribution.
- This script needs your personal token to work, you need to provide a valid GitHub personal access token as a secret named `PERSONAL_ACCESS_TOKEN` in your repository. Here's how you can do it:
-  Generate a GitHub personal access token:
-  Go to your GitHub account settings.
-  Select "Developer settings" from the …
> feat: add workflow script for prevent multiple issues 🔐

- public/css/style.css
- This PR is about fixing the image disortion of the Imagine AI Logo of our website.
| BEFORE | AFTER |
| :--: | :---: |
| ![before](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/481b700f-fd0a-467b-acee-d1c803493306) | ![after](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/6490a796-febc-4fa7-83b4-ec55f2c3df77) |
> fix: image disortion for logo image 🛠

- public/css/style.css
- views/contactUs.ejs
Added hamburger menu to contact-us page, updated style.css and contactUs.ejs.
Replace #549  with the issue number which is fixed in this PR
https://github.com/SurajPratap10/Imagine_AI/assets/76244494/981915df-b3f7-4e2e-b35d-84ef1f0bd0be
> Updating add hamburger menu to contact-us page

- public/css/style.css
Style ware added on the scrollbar.
https://github.com/SurajPratap10/Imagine_AI/assets/83147410/d921c7dc-a08b-423a-8e9d-eb60ca215fbf
> style added on scrollbar

- views/home.ejs
- Styling the heading of the website
- Making content more attractive and readable
> [GSSoC'23] Fonts added for the header

- views/includes/topToBottomScrollButton.ejs
- Styling the back to top arrow button
- Also fixing the hide and show functionality of the back to top arrow button
https://github.com/SurajPratap10/Imagine_AI/assets/114330097/d58f43f1-9d7f-4db9-99b5-6e91b09e9f24
> [GSSoC'23] Styling Back to Top Arrow Button

- views/includes/header.ejs
Hey @SurajPratap10 I have added favicon to the website. Please review my pr and merge it. Thank you!
> Added favicon to the website

- public/css/style.css
- views/signup.ejs
- Added some gap between login, signup forms, and footer
- Removed some unnecessary css of the forms from the code
> Added gap between forms and footer

- views/includes/footer.ejs
> copyright improvement

- views/includes/navbar.ejs
> home logo navigation added

- index.js
1) To address the duplicate app.use(passport.initialize()) and app.use(passport.session()) lines , i  removed the duplicate lines from your code.
2) To add error handling in the Google Strategy callback, I modified the callback function in the GoogleStrategy configuration.
> Two changes in this code al line 40 to 44 and 66 to 87

- views/imagineAi.ejs
> margin added

- readme.md
Previous : 
Updated :
Website Live : https://imagine-ai-30mq.onrender.com/
Issue No. #611
> Update readme.md and Deployment Link

- views/includes/topToBottomScrollButton.ejs
Hey @SurajPratap10 I have improved the UI of the scroll to top button. Please review my pr and merge it. Thank you!
[screen-capture.webm](https://github.com/SurajPratap10/Imagine_AI/assets/100675296/9ac46f10-1aef-416c-823e-38ad7ca89401)
> Improved the UI of the scroll to top button

- .env
- index.js
- views/imagineAi.ejs
This pull request fixes the callback URL issue that was causing the website to redirect to `localhost:5000` after Google authentication. The issue was resolved by updating the Google auth callback URL in the `.env` and `index.js` files to `https://imagine-ai-17zf.vercel.app/auth/google/callback`.
**Changes Made:**
- Updated the Google auth callback URL in `.env` and `index.js` to `https://imagine-ai-17zf.vercel.app/auth/google/callback`.
> Fixed Callback URL Issue

- public/css/style.css
- views/includes/navbar.ejs
added underline effects over the hover effect
https://github.com/SurajPratap10/Imagine_AI/assets/83147410/afd0ebcf-a423-48a9-9a36-750367c342d1
> added underline effects over hover effect

- public/css/fixed responsiveness newsletter.css
Fixed responsiveness fully for newsletter section.
- [ x] Tests have been added or updated to cover the changes
- [ x] Code follows the established coding style guidelines
> Fixed responsiveness newsletter.css

- public/js/main.js
- views/imagineAi.ejs
- views/includes/header.ejs
This pull request addresses the issue of the "Generate Image" button being stuck on loading in the ImagineAI website. The problem was caused by a race condition during the image generation process, leading to the button not updating its state correctly.
Changes Made:
1. Introduced asynchronous handling: Modified the code responsible for image generation to use asynchronous requests, ensuring smooth and non-blocking processing.
2. Implemented loading spinner: Added a loading spinner to the "Generate Image" button during the image generation process. This visual indicator informs users that the image is being processed and avoids the button from appearing unresponsive.
3. Button state update: Updated the "Generate Image" button's state properly after image generation completion, ensuring …
> Fixed Generate image stuck on loading error: URGENT 🚨

- views/imagineAi.ejs
- Fixed the missing mobile sidebar on Form page.
> fix: missing mobile sidebar on form page 🛠

- controllers/authController.js
Implemented exception handling in login logic.
This commit implements the exception handling in login logic which prevents unexpected crashes.
> Implemented exception handling in login logic.

- views/includes/footer.ejs
> added link to the logo in footer and navabr

- CODE_OF_CONDUCT.md
> removed mistakes and misspells form code_of_conduct (en-uk)

- views/includes/footer.ejs
Fixed the issue of copyright year. No dependency required.
> Added auto update feature for Copyright year

- views/includes/footer.ejs
> Fixed mistakes in footer

- CONTRIBUTING.md
Created CONTRIBUTING.md for the project keeping in mind readme and codeofconduct.md
> Created CONTRIBUTING.md for the project keeping in mind readme and codeofconduct.md

- public/css/style.css
Improve the background of the input section of the imgDescription
> improve the UI of the imageDescription section

- views/privacypolicy.ejs
> improved the privacy policy header that was cutting the navbar

- package-lock.json
- package.json
- public/css/style.css
- views/includes/navbar.ejs
#695
I have changed the entire alignment and spacing between nav elements, now they are looking more visually appealing and interactive, I have given new hover effects to the nav elements that completely enhance the UX experience.
695 is fixed in this PR
> Resolved #695

- public/css/style.css
- Improved and enhanced the Hover state of Social Icons on Footer, and refactored the style rules then prettified to maintain code consistency.
https://user-images.githubusercontent.com/92252895/258428289-676c3e94-e0ff-40ad-949a-e507af332fcb.mp4
> refactor: revamp hover states of social icons on footer 🪄✨ 

- views/contactUs.ejs
>  [Bug] - Made the placeholder visible

- index.js
- package-lock.json
- package.json
> Add Cors Policy

- views/home.ejs
- views/imagineAi.ejs
- views/includes/navbar.ejs
- `Added **alt attribute text in views/home.ejs, views/includes/navbar.ejs and views/imagineAi.ejs Files.**`
> fix: Added missing alt text in Multiple EJS FILES

- package-lock.json
- views/home.ejs
This pull request adds a new functionality that sends an email notification to the AI website owner whenever a new subscriber signs up for the newsletter. This feature enhances user engagement and ensures that the website owner is informed about new subscribers in a timely manner.
- Added new code to the newsletter sign-up form that triggers an email notification to the website owner.
- Integrated an email service API to handle the email sending process securely.
- Implemented error handling and fallback mechanisms to ensure robust email delivery.
1. Sign up for the newsletter using a new email address.
2. Verify that an email notification is sent to the website owner's specified email address.
3. Confirm that the email contains the relevant subscriber information and timestamp.
- The …
> Added email service to newsletter

- views/imagineAi.ejs
Hello @SurajPratap10 ,
I have fixed the footer dark mode issue which is in the ImagineAI Page.
- You can merge this
> Fixed Dark Mode Issue {ImagineAI}

- public/css/style.css
- Fixes the improper background color changing behaviour of Mail Subscription Form on About and Contact Page during toggling Theme.
|BEFORE|AFTER|
|:---:|:---:|
| ![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/e8101fbb-cceb-4846-843a-8488869aa5cf) | ![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/34664da2-121b-497d-85c6-ce1486171693) |
> fix: mail form background changing during theme toggle 🔧👷🏻 

- public/css/style.css
- views/home.ejs
- Revamped the design of Newsletter Signup Section, Built with Mobile first Workflow.
- So it ensures responsive for Mobile and Desktop.
|DESKTOP VIEW - OLD| DESKTOP VIEW - NEW|
|:---:|:---:|
|![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/e50266c6-68b4-46be-9ee5-5bf1aefdad34) | ![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/910c32db-4dfb-45ff-b2f5-db77f0d615e7) |
|MOBILE VIEW - OLD| MOBILE VIEW - NEW|
|:---:|:---:|
| ![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/9b80bcdb-5d7a-408f-9947-0f43d5a5d5b2) | ![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/88c2431a-1f7e-4492-a302-a2f9d8795e13)
> feat: revamp newsletter sign up section 🪄✨ 

- views/includes/navbar.ejs
I have Added Github btn which is redirect to Project Repository
> feat:  GitHub button Navbar ✨

- public/js/validation.js
- views/contactUs.ejs
I would like to propose a feature enhancement for the contact.html page, which is one of the main pages of our website. which may discourage users from filling out the project submission form. Furthermore, upon submitting the form, users did not get any message about whether the form is submitted or not. 
plz review the changes @SurajPratap10 
https://github.com/SurajPratap10/Imagine_AI/assets/99162236/e02ddad6-025b-4224-8dc7-9b8a732869c9
> No response on click submit button in contact us page.

- views/imagineAi.ejs
as it does not contain any image so it not for use in that section.
updated one
https://github.com/SurajPratap10/Imagine_AI/assets/114687502/9038a4ce-933b-49ac-a74b-ef747f8c4f8f
> bug is resolved img section is removed

- views/imagineAi.ejs
Reverts SurajPratap10/Imagine_AI#756
> Revert "bug is resolved img section is removed"

- views/includes/navbar.ejs
Reverts SurajPratap10/Imagine_AI#754
> Revert "feat:  GitHub button Navbar ✨"

- .github/workflows/issues.yml
- Fixed Wrong repository credentials (links and details) on greetings workflow
> refactor: fix wrong repository's credentials on greetings workflow 🔧✅ 

- CONTRIBUTING-GUIDELINES.md
I added Guideline for  `commit lint `if you want to commit please follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
> feat: add docs 📃

- package-lock.json
- routes/viewRoutes.js
- views/includes/navbar.ejs
- views/includes/sidebar.ejs
- views/team.ejs
Made the desired changes
Closes issue #711 
https://github.com/SurajPratap10/Imagine_AI/assets/127319225/a6372ada-8522-4883-97c4-1398f694aa51
- [ x] Tests have been added or updated to cover the changes
- [ x] Documentation has been updated to reflect the changes
- [x ] Code follows the established coding style guidelines
Just a small request, please consider this issue is considered to be of level 3 . It will help me very much.
Thank You.
> Added contributors list

- readme.md
- views/home.ejs
Added download button in the example image photos.
**Add Image Download button on the some exaples image** 
https://github.com/SurajPratap10/Imagine_AI/assets/86224794/80cd79ca-5e59-4dbb-a321-779b5407f3a4
> Example Image Download Button

- views/includes/sliderr.ejs
- Revamped the slider design to enhance the testimonials section of About Us Page
|||
|:--:|:---:|
|**BEFORE**|![image](https://user-images.githubusercontent.com/92252895/258970059-5f12058c-3828-4e87-8e5c-fa71e7c1a10c.png)|
|**AFTER**|![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/b08ac5bc-5b2a-4310-afa9-b91519c43ae0)|
> feat: revamp testimonials sliding animation design 🪄✨ 

- views/home.ejs
Our ImagineAI website aims to provide users with a seamless experience in generating images using the OpenAI API. To enhance user onboarding and guide them through the process of obtaining an API key and generating images through prompts, we propose adding a tutorial video to the website.
We suggest creating a comprehensive tutorial video that walks users through the following key steps:
1. **Obtaining OpenAI API Key**: The tutorial will guide users on how to sign up for an OpenAI account (if not already done) and navigate to the API section. It will demonstrate the process of creating a new API key, highlighting the importance of securing and protecting the key.
2. **Setting Up API Key**: The tutorial will provide clear …
> Added  tutorial video with custom thumbnail

- views/contactUs.ejs
> Improved CONTACT US sections contact card

- views/team.ejs
Contibutor page issue resolved
> Contibutor page issue resolved

- views/contactUs.ejs
- Revamped the Contact Us form design to enhance accessibility and user experience.
- Now the Contact Us form will have a better responsive design compared to old form design.
- This PR is to improve the overall design of Contact Us from by revamping per UI & UX Principles
|BEFORE|AFTER|
|:---:|:---:|
|![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/ea8729aa-feed-4c03-a0ba-11bcc07af62c)| ![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/6e5538f6-417d-4f9b-aa8a-9d34507d6a7f) |
> feat: revamp contact us form design with enhancements 🪄✨ 

- public/css/errorStyle.css
Update
Provide Smoothness while Scrolling using CSS
> Provide Smoothness while Scrolling

- .github/pull_request_template.md
- This PR is about improving the Pull Request Template by adding descriptive comments and dedicated screenshot block for tracking before and after changes made by contributors.
> refactor: improve pull request template with enhancements 📝🔍 

- readme.md
I have added the table of contents and changed the order of the readme . I have enhanced the description of the project and added pictures of the different pages of the website. I have also removed the image icons and solved the issue.
- [] Tests have been added or updated to cover the changes
- [] Code follows the established coding style guidelines
- [] All tests are passing
> Add content and arrange in order.

- .husky/commit-msg
- package-lock.json
- package.json
I have init the `commitlint` in Your Project if you want to add customer rule you can checkout [Commit Lint Official Docs](https://commitlint.js.org/#/)
> feat: commitlint init ✨

- views/team.ejs
> The title text as well as other texts in community section changed

- readme.md
Added a dynamic svg in contributors section
Closes: #808 
| ![Image](
) | ![Image](
) |
> feat: Added dynamic contributors section

- views/home.ejs
- views/includes/sidebar.ejs
Making the tutorial section responsive responsive in home page and improving the css of sidebar
| ![Screenshot (305)](https://github.com/SurajPratap10/Imagine_AI/assets/76244494/b1ba88d2-681a-4c2d-9863-fed2cdbe21be) | ![Screenshot (307)](https://github.com/SurajPratap10/Imagine_AI/assets/76244494/4dfa568a-8091-4e4e-887f-58a95a29355a) |
> style: update style of home.ejs and sidebar.ejs

- views/home.ejs
- views/includes/sidebar.ejs
Reverts SurajPratap10/Imagine_AI#822
> Revert "style: update style of home.ejs and sidebar.ejs"

- public/css/style.css
| ![Image](image-link) | ![Image](image-link) |
> the newsletter get properly aligned(unwanted gap removed)

- views/home.ejs
> one unwanted segment area  removed

- views/includes/topToBottomScrollButton.ejs
> changing hover for back to top button

- views/team.ejs
In this pull request, I have introduced an engaging and visually appealing 3D animation effect to the contributors' section on the Imagine AI website. By leveraging CSS animations and transformations, I've transformed the contributor avatars into dynamic, interactive elements that respond to user interaction. Each contributor's profile image now smoothly flips to reveal additional information about them, creating an immersive and captivating experience for users.
The animation effect is achieved through a combination of CSS classes and transitions, resulting in a seamless flip from the front side (avatar) to the back side (profile information) of each contributor box. This enhancement adds a touch of innovation and modernity to the Imagine AI website, enhancing user engagement and …
> Added 3d Animations to  Contributors

- readme.md
I have removed the extra entry in Table of Contents.
This PR is part of GSSoC'23.
| ![259771234-569e6e3d-1e2b-462c-9059-b7a318d9b764](https://github.com/SurajPratap10/Imagine_AI/assets/89148144/505dd392-4d30-444f-b138-262e0ff7b884) | ![Screenshot 2023-08-10 220417](https://github.com/SurajPratap10/Imagine_AI/assets/89148144/5384f098-c086-4a40-8b9b-e711281e3252) |
> Fix Table of Contents

- package-lock.json
- package.json
Reverts SurajPratap10/Imagine_AI#863
> Revert "chore(deps): bump openai from 4.4.0 to 4.5.0"

- package-lock.json
- package.json
Reverts SurajPratap10/Imagine_AI#868
> Revert "chore(deps): bump @mui/styles from 5.14.7 to 5.14.9"

- package-lock.json
- package.json
Reverts SurajPratap10/Imagine_AI#867
> Revert "chore(deps): bump mongoose from 7.4.4 to 7.5.1"

- views/home.ejs
This pull request resolves two issues:
1. **Iframe Width on Larger Screens:**  
The iframe previously had a fixed width of 940px, causing layout issues on larger displays. I have updated the iframe width to `100%`, allowing it to take up the full width of its container on all screen sizes.  
**Fixes**: #1121 
2. **Newsletter Input Field and Validation:**  
- The input field for the newsletter was blending in with the background, making it difficult to locate. I have updated the input's background color to white for better visibility.
- I also added proper validation to ensure that users must enter a valid email address before submitting the form. If the input is left empty or an invalid email is entered, an error message will now be displayed instead of allowing the form to submit. …
> Fix Iframe Width and Newsletter Validation & Input Visibility

- .husky/commit-msg
- package-lock.json
- package.json
- views/contactUs.ejs
Applied styling on icons and improved the Contact Us details section with a hover effect.
- changed the style of icons
- Applied the animation on the Contact Us details section cards
- upgrade icon's
- fix the overflowing details
fix issue #1120
> Improved the contact us details section

- public/css/style.css
This PR introduces a hover effect and box-shadow styling to the navbar elements, making them more visually interactive.
| [Before Changes] (https://drive.google.com/file/d/1aXpCh0_jdbXAu-55lM71ymkmo7HMBsIK/view?usp=drive_link) | [After Changes] (https://drive.google.com/file/d/1CHJ5-lslXAVvlz3WCtAIx7RY0gm7gmNu/view?usp=drive_link) |
> feat: Add hover effects for improved interactivity #1118

- public/css/style.css
This pull request addresses the issue of inconsistent font usage across various pages in the application. The cursive font has been replaced with Montserrat, a more modern and readable sans-serif font, ensuring a cohesive and professional appearance throughout the user interface.
#1140 
1. Tests have been added or updated to cover the changes
2. Documentation has been updated to reflect the changes
3. Code follows the established coding style guidelines
4. All tests are passing
This pull request resolves the issue related to inconsistent font styles, enhancing the overall user experience.
> Fixed inconsistent font issue on page from cursive to Montserrat for a cleaner, more modern look

- views/contactUs.ejs
The email was too conjusted in footer of contact us page. 
|![image](https://github.com/user-attachments/assets/a2ff3d16-85e5-4bc3-88ca-604e19dbe16e) | ![image](https://github.com/user-attachments/assets/6392f9c0-279c-422c-93f9-6bbd1e4e08c0)
> corrected email in footer of contactUs page

- views/login.ejs
Reduced the size of google, fb, twitter
| ![image](https://github.com/user-attachments/assets/ccbdf85a-97a2-4a2f-b035-d40edc7912ed) | ![image](https://github.com/user-attachments/assets/168fac3f-9adb-4a14-b15c-cfb3757cb9f3) |
> Social Media login fixed

- views/includes/sidebar.ejs
#1168 
| ![image](https://github.com/user-attachments/assets/60bd143b-bee0-4d18-a0f7-98db339cbcfe) | ![image](https://github.com/user-attachments/assets/89201e2e-1615-49c4-8b89-6e19ad0ee04f) |
> [style]: Hamburger overflow even after click and close button not working

- package-lock.json
- package.json
- views/home.ejs
- views/includes/header.ejs
- views/includes/navbar.ejs
i have adde gsap sliding down animation to navbar and sliding in to the homepage 
https://github.com/user-attachments/assets/ae7701c1-6752-47e3-b7d3-4277333a45e2
> [UI ENHANCEMENT] : Added gsap animatin to homepage & navbar

- views/team.ejs
This pull request resolves the navbar size issue and includes additional enhancements to improve the overall look and feel of the page. The following changes have been implemented:
1. **Fixed Navbar Size:**
- Adjusted the height of the navbar to ensure it remains consistent and proportional across different screen sizes.
- Modified padding and margins to create a balanced appearance that integrates seamlessly with the rest of the page.
**Screenshots:**  
**Closing Issues:**  
This pull request resolves the navbar size issue and improves the overall page design:
- Closes #1180
> Fix Navbar Size and Enhance Page Design

- views/aboutUs.ejs
- views/slider.ejs
This pull request addresses the overflow issue in the testimonial section by dynamically adjusting the height and enhancing the user experience. The following changes have been implemented:
1. **Dynamic Height Adjustment:**
- Set the height of the testimonial section to `auto` to allow it to expand according to the content size, ensuring no vertical overflow occurs.
- Added appropriate padding to give the content enough breathing space and maintain consistency with the overall design.
2. **Responsive Design Implementation:**
- Made sure the testimonial section is fully responsive across all devices (desktop, tablet, and mobile).
- Adjusted CSS rules to maintain layout consistency on different screen sizes, ensuring the section remains visually appealing and functional.
3. **Tested Across …
> Fixees the width of the testimonial section

- package-lock.json
- views/aboutUs.ejs
- views/contactUs.ejs
- views/home.ejs
- views/imagineAi.ejs
- views/login.ejs
- views/privacypolicy.ejs
- views/signup.ejs
- views/slider.ejs
- views/team.ejs
the chatbot has been added and its working aswell.
@SurajPratap10 can you please review this , thank you!
> issue#1197 solved , chatbot added

- views/login.ejs
The show password button was at the center of password field, it was shifted to right.
> Solved issue #1144

- package-lock.json
- package.json
- public/css/style.css
- views/login.ejs
- views/signup.ejs
hey @SurajPratap10 
I have made the changes for issue no #1205 
I have changed the ui of sign in and sign up , kindly check
add the labels : gssoc extd , hacktoberfest
If you like my work please add level 3 label
> Signin Signup ui fixed

- public/css/style.css
This pull request introduces several enhancements to the user interface:
**H1 Heading:**
- Added a white glow effect on hover for the heading.
- Implemented a slight size increase (to 105%) on hover for better emphasis.
**Image:**
- Added a smooth scaling effect on the image, enlarging it to 110% when hovered over for a dynamic interaction.
These changes aim to improve the visual appeal and interactivity of the page, enhancing the overall user experience.
fixes: #1200 
Kindly merge it and assign me the labels.
>  Add Hover Effects and Glow to Heading and Image

- public/css/silder.css
- public/css/style.css
- views/home.ejs
I fixes the issues in the cards border-radius and newsletter alignment.
Issue Number : #1186 
|        BEFORE        |       
| 
|        AFTER         |
| 
|
pls add label gssoc-ext, hacktoberfest-accpeted and level 
@SurajPratap10
> Fixes the Border radius Issues and Newsletter Alignment

- public/css/style.css
Changes to be committed:
#	modified:   public/css/style.css
In this pull request, I have implemented a hover effect on the heading to enhance its visual appeal. Previously, the heading appeared static and lacked interactivity, giving it a rather dull appearance.
**_Changes made:_**
Added a **hover effect** that transitions the text color and introduces a **subtle shadow**, creating a smooth ease-in/out animation.
This provides a more engaging user experience by making the heading visually dynamic and modern.
This update aims to improve the overall aesthetics of the page while maintaining a clean and professional look.
Please review the changes, and let me know if any adjustments are required.
> Enhance Main Heading with Dynamic Hover Effect for Improved Visual Appeal

- .env
- views/aboutUs.ejs
- views/contactUs.ejs
the navbar has been added to the contactus page.
#1226 issue has been solved.
@SurajPratap10 can you please review this
> ✨the navbar has been added ✨

- public/css/style.css
This pull request addresses issue #1228 by removing unnecessary `.di h1` styles that were causing the bottom bar in the UI to break. This fix ensures the UI layout is now stable and consistent.
- Removed unneeded `.di h1` styles
- Resolved UI layout issues with the bottom bar
https://github.com/user-attachments/assets/71f29f90-e016-40e0-8095-f145abfe4ce9
https://github.com/user-attachments/assets/896f2bf1-4dbd-4d19-9193-a0e6f5f46b16
> Remove unnecessary .di h1 styles causing UI bottom bar issues

- views/includes/topToBottomScrollButton.ejs
|![image](https://github.com/user-attachments/assets/66264684-e4b0-47e8-bcb5-20a06c70b7d0) | ![image](https://github.com/user-attachments/assets/e599f112-ae25-44be-b247-bc017dcccd31) |
> Fixed overlapping of arrow and chatbot icon

- package-lock.json
- package.json
- routes/viewRoutes.js
- views/forgot-password.ejs
- views/login.ejs
Description
This PR introduces the Password Recovery feature, helping users regain access to their accounts seamlessly.
Fixes #1243 
Screenshots
Before:
no Forgot Password? option or page.
After:
https://github.com/user-attachments/assets/4a3b7d15-356a-42ad-97a9-cbfba927751b
> recovery-password-feature

- views/home.ejs
Reverts SurajPratap10/Imagine_AI#1252
> Revert "Added expand button for sample images"

- .env
- controllers/feedbackController.js
- index.js
- package-lock.json
- package.json
- routes/feedback.js
- routes/viewRoutes.js
- views/feedback.ejs
- views/includes/navbar.ejs
Added a feedback page where a user can leave their valuable suggestions for us to improve the website.
Implements a feedback issue which can take a user's feedback and send it to the project owner via mail , requires the project maintainers email and password as environment variables.
Required dependancy :
- nodemailer
Responsive
- [ x] Tests have been added or updated to cover the changes
- [ x] Documentation has been updated to reflect the changes
- [ x] Code follows the established coding style guidelines
> added feedback feature

- package-lock.json
- views/feedback.ejs
As you can see below video demo Footer is not available in Feedback page, So i add complete Footer with proper alaignment and proper navigation link.
Before:
After adding footer with proper alaignment and proper navigation:
https://github.com/user-attachments/assets/e6717d77-b937-4fb6-84f7-469de19126f4
> Adding Footer in Feedback page

- .env
- package-lock.json
- views/aboutUs.ejs
- views/alan.ejs
- views/contactUs.ejs
- views/feedback.ejs
- views/forgot-password.ejs
- views/home.ejs
- views/imagineAi.ejs
- views/intro.ejs
- views/login.ejs
- views/privacypolicy.ejs
- views/signup.ejs
- views/slider.ejs
- views/team.ejs
@SurajPratap10 can you please review this update.
#1266 has been solved.
https://github.com/user-attachments/assets/3a59fe60-286f-4040-bb21-01bb74dd48a6
> ✨multi translate system added.✨

- contributor/contributor.css
- contributor/contributor.html
- contributor/contributor.js
- index.js
- views/includes/footer.ejs
@SurajPratap10 can you -please review this update.
#1265 solved.
https://github.com/user-attachments/assets/f03f24d7-e8c8-485d-a87a-b53fd95cfd15
> ✨contributor page has been added✨

- views/contactUs.ejs
Add Navbar in Contact Us page in mobile view
| 
| 
|
> add_nav_in_contact_page_in_mobile_view

- public/css/style.css
Text is not visible on Contact Us, About Us Page.   I've changed the text properties which enhances them and also looks more clear.
Before:
After:
Before:
After:
Before:
After:
- [ x] Tests have been added or updated to cover the changes
- [ x] Code follows the established coding style guidelines
> Enhance the text-visibility of  Contact Us, About Us Page.

- .github/workflows/issue_open_close.yml
- .github/workflows/pr_merged.yaml
Closes #1300 
1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**
Using this workflows makes you'r repo more interactive ! @SurajPratap10 
_**Note**_: Add all the labels and assign me to this PR !!
Can you please upgrade it to level3! i added a lot of use full stuff!
> Github actions for more connectivity!

- views/aboutUs.ejs
- views/contactUs.ejs
- views/home.ejs
- views/imagineAi.ejs
- views/privacypolicy.ejs
- views/signup.ejs
- views/slider.ejs
- views/team.ejs
#1305
Add Chatbot Functionality to IMAGINE - AI
#1305 
|
https://github.com/user-attachments/assets/61cfdcad-5d2d-4677-8fb3-f984e7e9bf0d
> Add Chatbot Functionality to IMAGINE - AI

- readme.md
I Added Stargazers and forkers to Readme.md✨
> Added Stargazers and forkers to Readme.md✨
